<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/directives/payment-options.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/directives/loading-spinner.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/filters/money-format.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/filters/order-status.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/filters/payment-name.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/services/stripe-checkout.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/services/order-status.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/services/payment-name.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/services/window-splash.php' );?>
<?php include_once( MODULESPATH . '/nexo/inc/angular/order-list/controllers/orders-list.php' );?>