<?php $this->load->module_include( 'nexo', 'create-item-fields' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.config.html5' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.config.route' );?>
<?php $this->load->module_include( 'nexo', 'angular.order-list.directives.loading-spinner' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.directives.item-variations' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.directives.loader' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.itemTypes' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.providers' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.options' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.barcode-options' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.raw-to-options' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.tabs' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.factories.fields' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.run' );?>
<?php $this->load->module_include( 'nexo', 'angular.items.controllers.items' );?>
